execute_process(COMMAND "${NM}" -D --defined-only "${LIBRARY}"
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Cannot inspect native exports: ${error}")
endif()
string(REGEX MATCHALL "[^\n]+" lines "${output}")
set(actual)
foreach(line IN LISTS lines)
  string(REGEX REPLACE "^.* " "" symbol "${line}")
  list(APPEND actual "${symbol}")
endforeach()
list(SORT actual)
set(expected eo_cancel eo_close eo_evaluate eo_free eo_open)
if(NOT actual STREQUAL expected)
  message(FATAL_ERROR "Public ABI exports differ: ${actual}")
endif()
